version: "3.8"
services:
  app:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - app/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mongo
    env_file: 
      - app/.env
    volumes: 
      - .:/app/
